# CMake toolchain file for portable MinGW-w64
# Generated by download_mingw_portable.py

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Specify the cross compiler
set(CMAKE_C_COMPILER "C:/Users/mail/dev/personal/teensy_ambisonic_microphone/odas_py/mingw-portable/mingw64/bin/x86_64-w64-mingw32-gcc.exe")
set(CMAKE_CXX_COMPILER "C:/Users/mail/dev/personal/teensy_ambisonic_microphone/odas_py/mingw-portable/mingw64/bin/x86_64-w64-mingw32-g++.exe")
set(CMAKE_RC_COMPILER "C:/Users/mail/dev/personal/teensy_ambisonic_microphone/odas_py/mingw-portable/mingw64/bin/x86_64-w64-mingw32-windres.exe")

# Where to find the target environment
set(CMAKE_FIND_ROOT_PATH "C:/Users/mail/dev/personal/teensy_ambisonic_microphone/odas_py/mingw-portable/mingw64")

# Adjust the behavior of FIND_XXX() commands
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Specify the ranlib tool
set(CMAKE_RANLIB "C:/Users/mail/dev/personal/teensy_ambisonic_microphone/odas_py/mingw-portable/mingw64/bin/x86_64-w64-mingw32-ranlib.exe")
set(CMAKE_AR "C:/Users/mail/dev/personal/teensy_ambisonic_microphone/odas_py/mingw-portable/mingw64/bin/x86_64-w64-mingw32-ar.exe")

# Set the resource compiler
set(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> -O coff <FLAGS> <DEFINES> <INCLUDES> <SOURCE> <OBJECT>")
